#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tetrim.Resource", IsApplication=true)]

namespace Tetrim
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int move_bottom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int move_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int move_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int move_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int turn_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int turn_right = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060024
			public const int OpponentGridView = 2131099684;
			
			// aapt resource value: 0x7f060037
			public const int PlayerGridView = 2131099703;
			
			// aapt resource value: 0x7f060007
			public const int alertContainer = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int alertContent = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int alertTitle = 2131099656;
			
			// aapt resource value: 0x7f060050
			public const int backButton = 2131099728;
			
			// aapt resource value: 0x7f06000a
			public const int buttonLayout = 2131099658;
			
			// aapt resource value: 0x7f060036
			public const int buttonMoveDown = 2131099702;
			
			// aapt resource value: 0x7f06003b
			public const int buttonMoveFoot = 2131099707;
			
			// aapt resource value: 0x7f060035
			public const int buttonMoveLeft = 2131099701;
			
			// aapt resource value: 0x7f06003a
			public const int buttonMoveRight = 2131099706;
			
			// aapt resource value: 0x7f060034
			public const int buttonTurnLeft = 2131099700;
			
			// aapt resource value: 0x7f060039
			public const int buttonTurnRight = 2131099705;
			
			// aapt resource value: 0x7f060053
			public const int changeNameButton = 2131099731;
			
			// aapt resource value: 0x7f06003c
			public const int column1 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int column2 = 2131099709;
			
			// aapt resource value: 0x7f060052
			public const int deleteFriendsButton = 2131099730;
			
			// aapt resource value: 0x7f060054
			public const int deleteHighScoresButton = 2131099732;
			
			// aapt resource value: 0x7f060006
			public const int devicesLayout = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int enemyGrid = 2131099683;
			
			// aapt resource value: 0x7f06004e
			public const int exitButton = 2131099726;
			
			// aapt resource value: 0x7f060003
			public const int friendsDevices = 2131099651;
			
			// aapt resource value: 0x7f060032
			public const int gridButtonLayout = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int layoutButtonsLeft = 2131099699;
			
			// aapt resource value: 0x7f060038
			public const int layoutButtonsRight = 2131099704;
			
			// aapt resource value: 0x7f06000d
			public const int layoutGame = 2131099661;
			
			// aapt resource value: 0x7f06003e
			public const int layoutLeftGrid = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int layoutRightGrid = 2131099711;
			
			// aapt resource value: 0x7f06001a
			public const int level1 = 2131099674;
			
			// aapt resource value: 0x7f06002d
			public const int level2 = 2131099693;
			
			// aapt resource value: 0x7f06004a
			public const int linearLayout1 = 2131099722;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout2 = 2131099650;
			
			// aapt resource value: 0x7f060041
			public const int linearLayout3 = 2131099713;
			
			// aapt resource value: 0x7f060040
			public const int menuContainer = 2131099712;
			
			// aapt resource value: 0x7f06000b
			public const int negativeButton = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int newDevices = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int pairedDevices = 2131099652;
			
			// aapt resource value: 0x7f06001d
			public const int piece1 = 2131099677;
			
			// aapt resource value: 0x7f060030
			public const int piece2 = 2131099696;
			
			// aapt resource value: 0x7f06000f
			public const int player1layout = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int player1level = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int player1levelLayout = 2131099673;
			
			// aapt resource value: 0x7f060011
			public const int player1name = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int player1nameLayout = 2131099664;
			
			// aapt resource value: 0x7f06001e
			public const int player1piece = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int player1pieceLayout = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int player1rows = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int player1rowsLayout = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int player1rowsLevelLayout = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int player1score = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int player1scoreLayout = 2131099666;
			
			// aapt resource value: 0x7f060020
			public const int player2column1 = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int player2column2 = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int player2layout = 2131099679;
			
			// aapt resource value: 0x7f06002e
			public const int player2level = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int player2levelLayout = 2131099692;
			
			// aapt resource value: 0x7f060022
			public const int player2name = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int player2nameLayout = 2131099681;
			
			// aapt resource value: 0x7f060031
			public const int player2piece = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int player2pieceLayout = 2131099695;
			
			// aapt resource value: 0x7f06002b
			public const int player2rows = 2131099691;
			
			// aapt resource value: 0x7f060029
			public const int player2rowsLayout = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int player2score = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int player2scoreLayout = 2131099686;
			
			// aapt resource value: 0x7f06000e
			public const int playersLayout = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int positiveButton = 2131099660;
			
			// aapt resource value: 0x7f06004f
			public const int relativeLayout1 = 2131099727;
			
			// aapt resource value: 0x7f060000
			public const int root = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int rows1 = 2131099671;
			
			// aapt resource value: 0x7f06002a
			public const int rows2 = 2131099690;
			
			// aapt resource value: 0x7f060013
			public const int score1 = 2131099667;
			
			// aapt resource value: 0x7f060027
			public const int score2 = 2131099687;
			
			// aapt resource value: 0x7f060001
			public const int selectDeviceText = 2131099649;
			
			// aapt resource value: 0x7f06004d
			public const int settingsButton = 2131099725;
			
			// aapt resource value: 0x7f060051
			public const int settingsTitle = 2131099729;
			
			// aapt resource value: 0x7f06004b
			public const int singlePlayerButton = 2131099723;
			
			// aapt resource value: 0x7f060045
			public const int titleE = 2131099717;
			
			// aapt resource value: 0x7f060048
			public const int titleI = 2131099720;
			
			// aapt resource value: 0x7f060043
			public const int titleLayout = 2131099715;
			
			// aapt resource value: 0x7f060049
			public const int titleM = 2131099721;
			
			// aapt resource value: 0x7f060047
			public const int titleR = 2131099719;
			
			// aapt resource value: 0x7f060044
			public const int titleT = 2131099716;
			
			// aapt resource value: 0x7f060046
			public const int titleT2 = 2131099718;
			
			// aapt resource value: 0x7f06004c
			public const int twoPlayersButton = 2131099724;
			
			// aapt resource value: 0x7f060042
			public const int userNameText = 2131099714;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BluetoothConnection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GameMulti = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GameSingle = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int BTNotAvailable = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int BTNotEnabled = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int ConnectionImpossible = 2130968614;
			
			// aapt resource value: 0x7f040025
			public const int ConnectionLost = 2130968613;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040020
			public const int askName = 2130968608;
			
			// aapt resource value: 0x7f040013
			public const int askSure = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int askSureDeleteFriends = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int askSureDeleteHighScore = 2130968597;
			
			// aapt resource value: 0x7f040005
			public const int bottom_arrow = 2130968581;
			
			// aapt resource value: 0x7f040012
			public const int cancel = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int changeName = 2130968592;
			
			// aapt resource value: 0x7f040027
			public const int connection_back = 2130968615;
			
			// aapt resource value: 0x7f04000e
			public const int deleteFriends = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int deleteHighScores = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int down_arrow = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int exit = 2130968589;
			
			// aapt resource value: 0x7f04001f
			public const int gameOver = 2130968607;
			
			// aapt resource value: 0x7f04002e
			public const int game_request = 2130968622;
			
			// aapt resource value: 0x7f04002d
			public const int game_request_title = 2130968621;
			
			// aapt resource value: 0x7f040002
			public const int left_arrow = 2130968578;
			
			// aapt resource value: 0x7f040019
			public const int menu = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int newHighScore = 2130968604;
			
			// aapt resource value: 0x7f040017
			public const int noDialog = 2130968599;
			
			// aapt resource value: 0x7f04002c
			public const int none_found = 2130968620;
			
			// aapt resource value: 0x7f04002a
			public const int none_friend = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int none_paired = 2130968619;
			
			// aapt resource value: 0x7f040011
			public const int ok = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int onePlayer = 2130968586;
			
			// aapt resource value: 0x7f040021
			public const int pause = 2130968609;
			
			// aapt resource value: 0x7f040018
			public const int playAgain = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public const int playerHighScore = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int playerLoose = 2130968606;
			
			// aapt resource value: 0x7f04001a
			public const int playerScore = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int playerWin = 2130968605;
			
			// aapt resource value: 0x7f040032
			public const int reconnect_activity = 2130968626;
			
			// aapt resource value: 0x7f040022
			public const int resume = 2130968610;
			
			// aapt resource value: 0x7f040028
			public const int retry_connection = 2130968616;
			
			// aapt resource value: 0x7f040001
			public const int right_arrow = 2130968577;
			
			// aapt resource value: 0x7f040029
			public const int scanning = 2130968617;
			
			// aapt resource value: 0x7f04000c
			public const int settings = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int turn_left_arrow = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int turn_right_arrow = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int twoPlayers = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int up_arrow = 2130968580;
			
			// aapt resource value: 0x7f040031
			public const int waiting_for_opponent = 2130968625;
			
			// aapt resource value: 0x7f040008
			public const int welcome = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int welcomeUser = 2130968585;
			
			// aapt resource value: 0x7f040030
			public const int wrong_version = 2130968624;
			
			// aapt resource value: 0x7f04002f
			public const int wrong_version_title = 2130968623;
			
			// aapt resource value: 0x7f040016
			public const int yesDialog = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_TetrimDialogTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_TetrimTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
