#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tetris.Resource", IsApplication=true)]

namespace Tetris
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int move_bottom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int move_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int move_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int move_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int turn_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int turn_right = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001e
			public const int OpponentGridView = 2131034142;
			
			// aapt resource value: 0x7f050024
			public const int PlayerGridView = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int ProposedPiecesView = 2131034141;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button2 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int button3 = 2131034114;
			
			// aapt resource value: 0x7f050023
			public const int buttonMoveDown = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int buttonMoveFoot = 2131034152;
			
			// aapt resource value: 0x7f050022
			public const int buttonMoveLeft = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int buttonMoveRight = 2131034151;
			
			// aapt resource value: 0x7f050021
			public const int buttonTurnLeft = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int buttonTurnRight = 2131034150;
			
			// aapt resource value: 0x7f050009
			public const int button_scan = 2131034121;
			
			// aapt resource value: 0x7f050020
			public const int layoutButtonsLeft = 2131034144;
			
			// aapt resource value: 0x7f050025
			public const int layoutButtonsRight = 2131034149;
			
			// aapt resource value: 0x7f05000d
			public const int layoutPlayerNames = 2131034125;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout1 = 2131034143;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout2 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout3 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int myLayout = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int new_devices = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int paired_devices = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int player1level = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int player1name = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int player1rows = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int player1score = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int player2level = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int player2name = 2131034127;
			
			// aapt resource value: 0x7f05001c
			public const int player2rows = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int player2score = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int tableLayout1 = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int tableRow2 = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int tableRow3 = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int tableRow4 = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int textView31 = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int textView39 = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int textView40 = 2131034139;
			
			// aapt resource value: 0x7f050007
			public const int title_new_devices = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int title_paired_devices = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Accueil = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int BTNotAvailable = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int BTNotAvailableTitle = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int BTNotEnabled = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int BTNotEnabledTitle = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int ConnectionImpossible = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int ConnectionImpossibleTitle = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int ConnectionLost = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int ConnectionLostTitle = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int app_name = 2130968589;
			
			// aapt resource value: 0x7f040015
			public const int button_scan = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int checkboxText = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int connexionBluetooth = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int game_over = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int none_found = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int none_paired = 2130968593;
			
			// aapt resource value: 0x7f04000c
			public const int not_connected = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int not_connected_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int scanning = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int select_device = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int title_other_devices = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int title_paired_devices = 2130968595;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
